In [4]:
import numpy as np

arr = np.arange(24)
print(arr)
print(arr.ndim)

#每一个元素有三行四列,有两个元素
arr2 = arr.reshape(2,3,4)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape = (3,2)
print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
6
int64


In [14]:
arr1 = np.array([1,2,3,4,5],dtype='i1')
print(arr1)
print(arr1.itemsize)

arr2 = np.array([1,2,4,5,6],dtype='f')
print(arr2)
print(arr2.itemsize) #字节

[1 2 3 4 5]
1
[1. 2. 4. 5. 6.]
4


In [16]:
arr = np.array([1,2,3,4,5])
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

