In [1]:
import numpy as np

arr  = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr[1]

np.int64(1)

In [6]:
s = slice(2,7,1) #从下表2开始拿到下表7 但是不包括，然后一个一个抽
arr[s] 

array([2, 3, 4, 5, 6])

In [11]:
# start:stop:start

In [10]:
arr2 = arr[2:7:2]
arr2

array([2, 4, 6])

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2 = arr[2]
print(arr)
print('\n')
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


[7 8 9]


In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2 = arr[1:4:1]
print(arr)
print('\n')
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2 = arr[1:4:1]
s = slice(1,4,1)
print(arr[s])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
arr = np.arange(15)
arr.shape = (5,3)
print(arr)
print('\n')
print(arr[...,1]) #所有行和第二列
print('\n')
print(arr[4,...]) #所有列和第五行

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[ 1  4  7 10 13]


[12 13 14]
