In [41]:
import numpy as np

In [42]:
arr = np.array([1,2,3,4,5,6],ndmin=2)
arr

array([[1, 2, 3, 4, 5, 6]])

In [43]:
arr = np.array([3,2],dtype=int)

print(arr)

[3 2]


In [44]:
arr = np.zeros(5,dtype=int)
arr

array([0, 0, 0, 0, 0])

In [45]:
arr = np.zeros([3,2],dtype=int)
arr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [46]:
arr = np.zeros([2,2],dtype=[('x','i4'),('y','f')])
arr

array([[(0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.)]], dtype=[('x', '<i4'), ('y', '<f4')])

In [47]:
arr = np.ones([3,2],dtype='i4')
arr

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [48]:
arr = np.full([3,2],fill_value=1024,dtype='i4')
arr

array([[1024, 1024],
       [1024, 1024],
       [1024, 1024]], dtype=int32)

In [49]:
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [50]:
s = b"wujiafa zuishuai"
arr = np.frombuffer(s,dtype='S1',count=5,offset=2)
arr

array([b'j', b'i', b'a', b'f', b'a'], dtype='|S1')

In [51]:
#从迭代对象创建ndarray
x = [1,2,3,4,5,6]
z = iter(x)
print(z)
print(type(z))
arr = np.fromiter(z,dtype='f')
arr

<class 'list_iterator'>


array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [52]:
#创建等差数列
arr = np.linspace(1,10,10,dtype='i4')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [53]:
#创建等比数列
arr = np.logspace(1.0,2.0,10,dtype='f4')
arr

array([ 10.      ,  12.915497,  16.681005,  21.544348,  27.825594,
        35.938137,  46.41589 ,  59.948425,  77.42637 , 100.      ],
      dtype=float32)

In [56]:
#创建随机数
arr = np.random.rand()
print(arr,type(arr))

arr = np.random.rand(5)
arr

0.9495141503785575 <class 'float'>


array([0.73446811, 0.3736048 , 0.72821809, 0.04784834, 0.97317913])

In [57]:
arr = np.random.rand(3,2)
arr

array([[0.86390325, 0.21335756],
       [0.74898403, 0.27498992],
       [0.13173894, 0.53674545]])

In [58]:
#三维
arr = np.random.rand(3,2,2)
arr

array([[[0.40665918, 0.48846375],
        [0.14230829, 0.38477452]],

       [[0.051861  , 0.26797151],
        [0.41370754, 0.52042472]],

       [[0.2837136 , 0.72876462],
        [0.07442689, 0.4686389 ]]])

In [60]:
arr = np.random.random(3)
arr

array([0.27262446, 0.81865486, 0.76192504])

In [64]:
arr = np.random.randint(0,10,5)
arr

array([8, 6, 1, 8, 0], dtype=int32)

In [65]:
arr = np.random.randn()
arr

-1.8017384552617426

In [66]:
arr = np.random.randn(5)
arr

array([-0.4427889 ,  0.6633931 , -0.05339964,  1.00380351,  0.30776613])

In [67]:
arr = np.random.randn(2,4)
arr

array([[ 1.23891805,  0.70406051, -0.06292108, -0.30419713],
       [-1.37109296, -1.24324922,  0.99725488,  0.20169596]])

In [68]:
arr = np.random.normal(loc=1,scale=2,size=5)
arr

array([-0.85729461,  1.13821507, -1.19727634, -0.74783346, -2.66503631])