In [2]:
# 创建一个一位数组
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#元素类型要相同
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#多维数组
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9],ndmin=2)
arr
#规定最少二维数组

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
# dtype函数
arr = np.array([1,2,3,4,5],dtype='f4')
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [14]:
#结构化数据类型
student = np.dtype([("name","S20"),("age","i4"),("scroe","f4")])
arr = np.array([("tom",18,99.999999),("Lisa",5,100.00000000000)],dtype=student)
arr

array([(b'tom', 18, 100.), (b'Lisa',  5, 100.)],
      dtype=[('name', 'S20'), ('age', '<i4'), ('scroe', '<f4')])

In [15]:
arr = np.asarray([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
arr = np.asarray((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [19]:
arr = np.asarray([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])