In [5]:
import numpy as np

a = np.arange(12)
a.shape = (3,4)
print(a)
print('-----------------------')
for x in np.nditer(a):
    print(x,end=' ')
print(" ")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------
0 1 2 3 4 5 6 7 8 9 10 11  


In [9]:
b = a.T.copy(order = 'F') #C为行优先 F为列优先
print(b)
print('----------------------')
for x in np.nditer(b):
    print(x,end=",")
print("")

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
----------------------
0,1,2,3,4,5,6,7,8,9,10,11,


In [11]:
b = a.T.copy(order = 'F') #C为行优先 F为列优先
print(b)
print('----------------------')
for x in np.nditer(b,order = 'C', op_flags = ["readwrite"]):
    x[...] = x * 2
print(b)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
----------------------
[[ 0  8 16]
 [ 2 10 18]
 [ 4 12 20]
 [ 6 14 22]]
