In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#如歌我要0,0 1,1 2,2
print(arr[[0,1,2],[0,1,2]])

[1 5 9]


In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype='i1')
arr.shape = (4,3)
print(arr)
print('-------------------')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) #竖着看 0,0 0,2 3,0 3,2
print(arr[rows[0],cols[0]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-------------------
[1 3]


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype='i1')
arr.shape = (4,3)
print(arr)
print('-----------------------------')
print(arr[1:3,1:3])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-----------------------------
[[5 6]
 [8 9]]


In [26]:
print('-----------------------------')
print(arr[1:3,[1,2]])

-----------------------------
[[5 6]
 [8 9]]


In [27]:
print('-----------------------------')
print(arr[...,[1,2]])

-----------------------------
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


In [29]:
print('-----------------------------')
print(arr[1:3,...])

-----------------------------
[[4 5 6]
 [7 8 9]]


In [30]:
#布尔索引
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype='i1')
arr.shape = (4,3)

print(arr[arr>5])

[ 6  7  8  9 10 11 12]


In [42]:
arr = np.array([np.nan,1,2,np.nan,4,5,6])
print(arr)
print('---------------')
print(arr[~np.isnan(arr)])

[nan  1.  2. nan  4.  5.  6.]
---------------
[1. 2. 4. 5. 6.]


In [50]:
arr2 = [x for x in arr if not np.isnan(x)]
print(arr2)

[np.float64(1.0), np.float64(2.0), np.float64(4.0), np.float64(5.0), np.float64(6.0)]
