# **Day-1-作业**

### 1.创建一个长度为10的一维全为0的ndarray对象,然后让第五个元素等于1

In [7]:
import numpy as np

arr = np.zeros(10,dtype='int')

In [8]:
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 2.创建一个元素为从10到49（包含49）的ndarray对象,间隔为1

In [18]:
import numpy as np

arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
arr = np.linspace(10,49,40,dtype=np.int8)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49], dtype=int8)

### 3.将第二题的所有元素反转

In [17]:
import numpy as np

arr = np.arange(10,50)

arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 4.使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素 

In [20]:
import numpy as np

arr = np.random.random(size=(10,10))
arr

array([[0.94450428, 0.62929407, 0.03018898, 0.37708833, 0.82574266,
        0.65338465, 0.96068617, 0.52579332, 0.98742545, 0.07070904],
       [0.6749403 , 0.96992887, 0.49860911, 0.90629101, 0.19855936,
        0.5456436 , 0.44800597, 0.02852024, 0.69963246, 0.87392055],
       [0.03548654, 0.01285016, 0.2589261 , 0.80318171, 0.17427047,
        0.82620225, 0.20264912, 0.77303991, 0.4051984 , 0.69829742],
       [0.6521258 , 0.5200564 , 0.68927563, 0.69643073, 0.52864155,
        0.71590307, 0.01573766, 0.51691376, 0.16389523, 0.6723655 ],
       [0.28128202, 0.46511132, 0.94769499, 0.93704913, 0.67564656,
        0.63606971, 0.88783397, 0.66749629, 0.81905127, 0.87044543],
       [0.24268803, 0.92325027, 0.72654887, 0.74485694, 0.75023294,
        0.87118482, 0.44952264, 0.0974144 , 0.1170234 , 0.28354208],
       [0.64902801, 0.13487506, 0.12065062, 0.3413809 , 0.94231339,
        0.19590763, 0.94562769, 0.07615682, 0.58066343, 0.60228335],
       [0.45540909, 0.47062709, 0.3460052

In [22]:
print('max : ',arr.max())
print('min : ',arr.min())

max :  0.9874254465010186
min :  0.008143415599201842


### 5.创建一个10*10的ndarray对象,且矩阵边界全为1,里面全为0

In [98]:
import numpy as np

arr = np.full(shape=(10,10),fill_value=0,dtype=np.int8)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [99]:
arr[[0,-1],0:-1] = 1
arr[:,[0,-1]] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

### 6.创建一个每一行都是从0到4的5*5矩形

In [100]:
import numpy as np

arr = np.zeros((5,5))

arr += np.arange(5)

arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [101]:
arr = np.full(shape=(5,5),fill_value=0)

arr2 = np.arange(5)

arr += arr2 # 或者arr[:] = arr2

arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 7.创建一个范围在(0,1)之间的长度为12的等差数列,创建[1,2,4,8,16,32,64,128,256,512,1024]的等比数列

In [102]:
import numpy as np

arr = np.linspace(0,12,num=13,dtype=np.int8)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int8)

In [103]:
np.set_printoptions(suppress=True)
arr2 = np.logspace(0,10,num=11,base=2)
arr2

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

### 8.创建一个长度为10的正太分布数组np.random.rand并排列 

In [104]:
import numpy as np

arr = np.random.randn(10)
print('no sort : ',arr)

arr2 = np.sort(arr)
print('sort : ',arr2)

no sort :  [-1.13660221  0.13513688  1.484537   -1.07980489 -1.97772828 -1.7433723
  0.26607016  2.38496733  1.12369125  1.67262221]
sort :  [-1.97772828 -1.7433723  -1.13660221 -1.07980489  0.13513688  0.26607016
  1.12369125  1.484537    1.67262221  2.38496733]


### 9.创建一个长度为10的随机数组并将最大值替换为-100

In [105]:
import numpy as np

np.set_printoptions(suppress=True)
arr = np.random.randint(0,100,size=10)
print(arr)

arr_max = arr.max()
# 条件判断
cond = arr == arr_max
cond
arr[cond] = -100
arr

[23 94 11 28 74 88  9 15 18 80]


array([  23, -100,   11,   28,   74,   88,    9,   15,   18,   80],
      dtype=int32)

### 10.如何根据第三列大小顺序来对一个5*5矩阵排序? (考察（argsort()方法）)

In [111]:
import numpy as np

np.random.seed(10)
arr = np.random.randint(0,10,(5,5))
print('orginal : \n',arr)

# 查看第三列数据,并获取索引排序
print('\n the third col database is : ',arr[:,2])
# argsort()方法返回的是数组值从小到大的索引值

print('\n the third col database sorted : ',np.argsort(arr[:,2])) # 返回的是索引值

# 根据第三列索引排序,进行重新索引
print('\nbase on the third col, Then reindex is : \n',arr[np.argsort(arr[:,2])])

orginal : 
 [[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]
 [4 1 3 6 5]]

 the third col database is :  [0 8 4 8 3]

 the third col database sorted :  [0 4 2 1 3]

base on the third col, Then reindex is : 
 [[9 4 0 1 9]
 [4 1 3 6 5]
 [8 6 4 3 0]
 [0 1 8 9 0]
 [4 6 8 1 8]]


In [112]:
np.random.seed(10)
arr = np.random.randint(0,10,(5,5))
print('orginal : \n',arr)

orginal : 
 [[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]
 [4 1 3 6 5]]


In [113]:
index = arr[:,2].argsort()

arr[index]

array([[9, 4, 0, 1, 9],
       [4, 1, 3, 6, 5],
       [8, 6, 4, 3, 0],
       [0, 1, 8, 9, 0],
       [4, 6, 8, 1, 8]], dtype=int32)