# Day-1-作业

### 1.创建一个长度为10的一维全为0的ndarray对象,然后让第五个元素等于1

In [6]:
import numpy as np

arr = np.zeros(10,order='F',dtype='int')
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 2.创建一个元素为从10到49（包含49）的ndarray对象,间隔为1

In [9]:
import numpy as np

arr = np.arange(10,50,dtype='int')
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
arr = np.linspace(10,49,40,dtype='int')
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3.将第二题的所有元素反转

In [14]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 4.使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素 

In [16]:
arr = np.random.random(size=(10,10))
arr

array([[4.02743804e-01, 5.32629921e-04, 5.42201337e-01, 6.80347727e-01,
        9.01928296e-01, 1.05100105e-01, 7.78951064e-01, 5.94550370e-01,
        1.38493333e-01, 1.63352104e-01],
       [5.61314789e-02, 6.69521197e-01, 8.62858132e-01, 4.87336573e-01,
        8.88090964e-01, 3.39557131e-01, 1.38533469e-01, 9.69938477e-01,
        7.54321645e-01, 2.90083417e-01],
       [7.81792586e-01, 4.60570987e-01, 2.57317201e-01, 7.99995781e-01,
        7.35015713e-01, 3.10002851e-01, 4.44444616e-01, 9.38707038e-01,
        9.88861442e-01, 8.08242500e-01],
       [9.47893523e-01, 9.91117400e-01, 7.74005351e-01, 4.06348524e-01,
        7.73270325e-01, 5.01211232e-01, 1.07268600e-01, 1.72184355e-01,
        8.82344163e-01, 8.31539205e-01],
       [8.72505490e-01, 8.55118734e-01, 7.34699678e-01, 5.10142966e-01,
        2.63433868e-01, 5.06119224e-01, 5.47011894e-02, 4.04130315e-01,
        3.19385338e-01, 4.80109602e-01],
       [9.48282927e-01, 5.96887608e-01, 6.24707472e-01, 7.99231733e-01,
   

In [17]:
print('the max database is : ',arr.max())

print('\nthe min database is :',arr.min())

the max database is :  0.9911173998317601

the min database is : 0.0005326299208365803


### 5.创建一个10*10的ndarray对象,且矩阵边界全为1,里面全为0

In [18]:
arr = np.zeros(shape = (10,10),order='F',dtype='int')
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
arr[[0,-1],:] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [21]:
arr[:,[0,-1]] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 6.创建一个每一行都是从0到4的5*5矩形

In [27]:
arr = np.full((5,5),0)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
arr2 = np.arange(5)
arr[:] = arr2
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 7.创建一个范围在(0,1)之间的长度为12的等差数列,创建[1,2,4,8,16,32,64,128,256,512,1024]的等比数列

In [34]:
arr = np.linspace(0,12,num=13)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [46]:
np.set_printoptions(suppress=True)
arr2 = np.logspace(0,10,base=2,num=11)
arr2

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

### 8.创建一个长度为10的正太分布数组np.random.rand并排列 

In [48]:
arr = np.random.randn(10)
arr

array([ 0.89113596, -1.91732258, -0.56235881, -0.53054361, -0.44980615,
        0.62492249, -0.18092782,  0.06762087, -0.26810509,  0.52871189])

In [49]:
arr2 = np.sort(arr)
arr2

array([-1.91732258, -0.56235881, -0.53054361, -0.44980615, -0.26810509,
       -0.18092782,  0.06762087,  0.52871189,  0.62492249,  0.89113596])

### 9.创建一个长度为10的随机数组并将最大值替换为-100

In [65]:
arr = np.random.randint(0,100,size=10,dtype=np.int16)
arr

array([ 0, 56,  5, 61, 56, 99, 22, 46, 37,  4], dtype=int16)

In [66]:
arr_max = arr.max()
arr_max

np.int16(99)

In [67]:
cond = arr == arr_max
arr[cond] = -100
arr

array([   0,   56,    5,   61,   56, -100,   22,   46,   37,    4],
      dtype=int16)

### 10.如何根据第三列大小顺序来对一个5*5矩阵排序? (考察（argsort()方法）)

In [68]:
arr = np.random.randint(1,10,(5,5))
arr

array([[6, 5, 8, 2, 3],
       [1, 5, 4, 1, 4],
       [5, 4, 5, 5, 2],
       [4, 7, 2, 1, 1],
       [3, 7, 5, 6, 9]], dtype=int32)

In [69]:
print('the third col is : ', arr[:,2])

the third col is :  [8 4 5 2 5]


In [70]:
sort = arr[:,2].argsort()
print('the third col is : ',sort )

the third col is :  [3 1 2 4 0]


In [72]:
arr[sort]

array([[4, 7, 2, 1, 1],
       [1, 5, 4, 1, 4],
       [5, 4, 5, 5, 2],
       [3, 7, 5, 6, 9],
       [6, 5, 8, 2, 3]], dtype=int32)