# **Numpy数据引出**

### 列表没办法取[0:2] 没办法打印[3]

In [2]:
import numpy as np

In [3]:
arr = [1,2,3,4,5]
print('print:',arr)

print('print 1 database:',arr[0])

print('print last database:',arr[4])
print('print last database:',arr[-1])

print: [1, 2, 3, 4, 5]
print 1 database: 1
print last database: 5
print last database: 5


In [4]:
print('print 1-2 databse :',arr[0:2])

print('print 2 last database :',arr[-2:])

print 1-2 databse : [1, 2]
print 2 last database : [4, 5]


### 而numpy可以做到 打印[3]

In [5]:
arr_np = np.array(arr)
arr_np

array([1, 2, 3, 4, 5])

In [6]:
print('print 1 and 3 database : ',arr_np[[0,2]])

print('print 1 and 3 database : ',arr_np[[0,2]])
arr_np[[0,2]]

print 1 and 3 database :  [1 3]
print 1 and 3 database :  [1 3]


array([1, 3])

In [7]:
#打印大于3的
cond = arr_np >= 3
cond
arr_np[cond]

array([3, 4, 5])

# **Numpy数组创建**

In [10]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.zeros(shape = 5)

array([0., 0., 0., 0., 0.])

In [12]:
np.full(shape = 20, fill_value = 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
       3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [14]:
np.random.randint(0,100,size = 10)

array([21, 41, 58, 52, 13, 36, 38, 76, 58,  5], dtype=int32)

In [39]:
# 生成随机数
np.random.random(size = 20)

array([0.30525729, 0.1346032 , 0.0805699 , 0.51778599, 0.57618378,
       0.93033032, 0.39797247, 0.95030629, 0.14893496, 0.7575754 ,
       0.59841242, 0.23189297, 0.19117573, 0.55075131, 0.30268162,
       0.62631125, 0.48411263, 0.20060254, 0.29258737, 0.43278577])

In [20]:
# 正态分布/高斯分布
# 基准线为0有正数和负数
# 凸起来的取现是正太分布
# 平均值为0，标准差为1：标准差是波动
np.random.randn(10)

array([ 0.20600748,  0.71732992,  1.13241949, -0.32124195,  0.22494211,
        0.92729167, -0.49655658, -0.31373731,  0.83468178, -0.2985425 ])

In [24]:
# 等差数列
np.linspace(1,100,50) #意思是 1 到 100之间，分为50

np.linspace(1,99,50)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

**shift+tab是查看函数参数**

In [34]:
# 等比数列
# 不显示科学计数法
np.set_printoptions(suppress = True) #不显示科学计数法
np.logspace(0,10,base = 3,num = 11) # 1 - 10 之间的数字，2的倍数，base是倍数的意思 2,num等于份数

array([    1.,     3.,     9.,    27.,    81.,   243.,   729.,  2187.,
        6561., 19683., 59049.])

In [35]:
# 二维数组
np.random.randint(0,10,size = (3,5)) # 0-10之间 3行5列

array([[3, 3, 6, 1, 7],
       [2, 8, 1, 7, 2],
       [0, 0, 3, 4, 0]], dtype=int32)

In [37]:
# 三维数组
np.random.randint(0,10,size = (2,3,4)) # 0-10之间的数字，三维数组有三个中括号
# (2,3,4)的意思是2个三行四列的数据

array([[[9, 6, 1, 9],
        [6, 7, 3, 0],
        [3, 3, 7, 3]],

       [[4, 3, 0, 3],
        [6, 3, 1, 8],
        [9, 6, 3, 8]]], dtype=int32)

# **Numpy数据查看**

In [4]:
import numpy as np
arr = np.random.random(size = (3,5))
arr

array([[0.33194409, 0.6775755 , 0.42574309, 0.23892632, 0.20688822],
       [0.74527965, 0.52957729, 0.23844545, 0.5494812 , 0.16175388],
       [0.21200348, 0.36828068, 0.8174586 , 0.14333114, 0.51862365]])

In [11]:
arr.shape # 查看形状

(3, 5)

In [12]:
arr.dtype # 查看类型 

dtype('float64')

In [13]:
arr.ndim # 查看维度

2

### **计算机的0和1 ------>是位**
### **8个位------> 字节**
### **这个arr是float类型 64位数**
### **64 / 8 = 8,所以每个元素对应的字节是8,每个元素的大小是8**


In [14]:
arr.itemsize #每个元素的大小

8

# Numpy文件保存

In [18]:
range(0,10)

range(0, 10)

In [19]:
# 取range数据
for i in range(0,10,2): # 2代表间隔
    print(i,end=',')

0,2,4,6,8,

In [20]:
[i for i in range(0,10,2)] #列表生成式

[0, 2, 4, 6, 8]

In [21]:
arr = np.arange(0,10,2) # 2代表间隔
np.save('./data-1',arr)

In [24]:
np.load('./data-1.npy') #取出数据

array([0, 2, 4, 6, 8])

In [32]:
np.set_printoptions(suppress=True)
arr2 = np.logspace(0,10,base = 2,num = 11)
arr2

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [33]:
np.savez('./data-2.npz',x = arr, y = arr2) # savez存取多个，npz是压缩 x/y任意取名字

In [34]:
np.load('./data-2.npz')['x'] # 取x

array([0, 2, 4, 6, 8])

In [35]:
np.load('./data-2.npz')['y']

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [42]:
# 加载 .npz 文件
data = np.load('./data-2.npz', allow_pickle=True)

# 打印所有键和对应的值
for key in data.keys():
    print(f"Key: {key}, Value: {data[key]}")

Key: x, Value: [0 2 4 6 8]
Key: y, Value: [   1.    2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


# **Numpy数据类型**

In [43]:
# 整数
# 浮点数
# 字符串

In [45]:
arr = np.array([2,4,5],dtype = np.int16)
arr

array([2, 4, 5], dtype=int16)

In [46]:
arr = np.array([2,4,5],dtype = np.int32)
arr

array([2, 4, 5], dtype=int32)

### **内存相差八倍**

In [79]:
arr = np.random.randint(0,100,size = (100,50),dtype=np.int8)
np.save('./data(0,100)-int8',arr)
np.load('./data(0,100)-int8.npy')

array([[54, 54,  9, ..., 56, 59, 94],
       [42, 79, 17, ..., 29, 26, 43],
       [54, 33, 96, ..., 52, 33, 85],
       ...,
       [22, 78, 44, ..., 81, 42, 55],
       [45, 54, 71, ..., 19,  4, 79],
       [50,  9, 33, ..., 34,  0, 23]], dtype=int8)

In [80]:
arr = np.random.randint(0,100,size = (100,50),dtype=np.int64)
np.save('./data(0,100)-int64',arr)
np.load('./data(0,100)-int64.npy')

array([[58, 66, 85, ..., 18, 64, 80],
       [37, 88, 17, ..., 37,  8, 97],
       [21, 57, 30, ..., 70,  0, 86],
       ...,
       [83, 59, 40, ...,  8, 81, 82],
       [17, 68, 25, ..., 52, 74, 83],
       [54, 44, 54, ...,  1, 25, 38]])

### **无符号 uint，没有负数**

In [51]:
2**8 # -128 ~ 127 包含0 取不到128

256

In [54]:
arr1 = np.arange(-128,128,dtype = np.int8) # 到不了128
arr1

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [55]:
arr1 = np.arange(-128,130,dtype = np.int8) # 超过了就不能表示了
arr1

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [72]:
# 0 - 255 = 256个数字
arr2 = np.arange(-128,128)
# 将负数转换为等价的正数
# arr2 = np.mod(arr, 256).astype(np.uint8)
# arr2
arr2 = arr2.astype(np.uint8)
arr2

array([128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
       232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
       245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  5

In [73]:
arr1.dtype

dtype('int8')

In [77]:
# 转换其数据类型
arr3 = arr1.astype(np.float32) # arr1的数据类型还是没转变，只是生成了一个新的数组 可赋值给arr3
arr3.dtype

dtype('float32')

# **Numpy数组的运算**

In [115]:
nd = np.random.randint(0,10,size = (3,5))
nd

array([[8, 2, 8, 7, 5],
       [0, 5, 8, 6, 0],
       [2, 3, 6, 6, 3]], dtype=int32)

In [116]:
nd ** 3 # 三次方

array([[512,   8, 512, 343, 125],
       [  0, 125, 512, 216,   0],
       [  8,  27, 216, 216,  27]], dtype=int32)

In [117]:
np.power(nd,3) # 幂运算

array([[512,   8, 512, 343, 125],
       [  0, 125, 512, 216,   0],
       [  8,  27, 216, 216,  27]], dtype=int32)

In [118]:
nd / 2

array([[4. , 1. , 4. , 3.5, 2.5],
       [0. , 2.5, 4. , 3. , 0. ],
       [1. , 1.5, 3. , 3. , 1.5]])

In [119]:
nd % 2 # 取余

array([[0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1]], dtype=int32)

In [120]:
nd ** nd # 两个星号代表幂运算

array([[16777216,        4, 16777216,   823543,     3125],
       [       1,     3125, 16777216,    46656,        1],
       [       4,       27,    46656,    46656,       27]], dtype=int32)

In [121]:
nd > 5

array([[ True, False,  True,  True, False],
       [False, False,  True,  True, False],
       [False, False,  True,  True, False]])

In [122]:
nd == 5

array([[False, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [123]:
nd

array([[8, 2, 8, 7, 5],
       [0, 5, 8, 6, 0],
       [2, 3, 6, 6, 3]], dtype=int32)

In [124]:
nd += 100 # 在原来的基础上加上100
nd

array([[108, 102, 108, 107, 105],
       [100, 105, 108, 106, 100],
       [102, 103, 106, 106, 103]], dtype=int32)

In [125]:
nd2 = nd.astype(np.float32)
nd2 /= 3
nd2

array([[36.      , 34.      , 36.      , 35.666668, 35.      ],
       [33.333332, 35.      , 36.      , 35.333332, 33.333332],
       [34.      , 34.333332, 35.333332, 35.333332, 34.333332]],
      dtype=float32)

In [126]:
nd2 //= 3
nd2

array([[12., 11., 12., 11., 11.],
       [11., 11., 12., 11., 11.],
       [11., 11., 11., 11., 11.]], dtype=float32)

# **Numpy复制和视图**

In [130]:
arr = np.random.randint(0,100,size = (4,5))
arr

array([[37, 42, 91, 17, 78],
       [46, 68, 40, 64, 85],
       [43, 22, 20, 59, 42],
       [58,  1, 39, 65, 58]], dtype=int32)

In [132]:
arr2 = arr
arr2

array([[37, 42, 91, 17, 78],
       [46, 68, 40, 64, 85],
       [43, 22, 20, 59, 42],
       [58,  1, 39, 65, 58]], dtype=int32)

In [134]:
arr is arr2 # arr 和 arr2 是不相同名字但是相同内存的对象

True

In [135]:
arr2[0,0] = 1024

In [138]:
display(arr,arr2) # 命运共同体

array([[1024,   42,   91,   17,   78],
       [  46,   68,   40,   64,   85],
       [  43,   22,   20,   59,   42],
       [  58,    1,   39,   65,   58]], dtype=int32)

array([[1024,   42,   91,   17,   78],
       [  46,   68,   40,   64,   85],
       [  43,   22,   20,   59,   42],
       [  58,    1,   39,   65,   58]], dtype=int32)

In [139]:
a = np.random.randint(0,100,size = (4,5))
b = a.copy()

In [140]:
a is b

False

In [143]:
b.base is a

False

In [145]:
b.flags.owndata

True

In [146]:
a.flags.owndata

True

In [147]:
b[0,0] = 1024

In [149]:
display(a,b) # b变a不变

array([[91, 38, 24, 53,  5],
       [32, 17, 59, 41, 10],
       [26, 33, 98,  7, 42],
       [50, 31, 69, 71, 88]], dtype=int32)

array([[1024,   38,   24,   53,    5],
       [  32,   17,   59,   41,   10],
       [  26,   33,   98,    7,   42],
       [  50,   31,   69,   71,   88]], dtype=int32)

# **Numpy切片和索引**

## **一位数组的索引的切片**

In [152]:
arr = np.random.randint(0,100,size=10)
arr

array([93, 76, 81, 55, 79, 26, 62,  8, 66, 57], dtype=int32)

In [161]:
print(arr[0]) # 索引
print(arr[-1]) # 索引
print(arr[0:2]) # 切片
print(arr[[0,3,5]]) # 索引

93
57
[93 76]
[93 55 26]


In [164]:
print(arr[3:6])
print(arr[3:6:2]) #从3-6，2表示两个中取一个

[55 79 26]
[55 26]


In [166]:
arr[::2] # 每隔2个取1个

array([93, 81, 79, 62, 66], dtype=int32)

In [167]:
arr[::-1] # 逆序

array([57, 66,  8, 62, 26, 79, 55, 81, 76, 93], dtype=int32)

In [169]:
arr[::-3] # 逆序 每隔3个取1个

array([57, 62, 55, 93], dtype=int32)

## **二维数组的索引和切片**

In [170]:
arr2 = np.random.randint(0,100,size = (3,5))
arr2

array([[95, 81, 97, 63, 10],
       [88, 81, 80, 10, 84],
       [ 3, 31,  9, 59, 63]], dtype=int32)

In [173]:
# 逗号隔开 取97 第一行第三列
arr2[0,2]

np.int32(97)

In [176]:
arr2[1,[1,2]] #第二行的第二第三个数据

array([81, 80], dtype=int32)

In [181]:
# 第二行和第三行以及第四列和第五列的数据
# 索引和切片配合使用
arr2[[1,2],3:]

array([[10, 84],
       [59, 63]], dtype=int32)

In [190]:
arr2[1::-1,[0,1]] # 先降序，然后取二三行的 一二列 

array([[88, 81],
       [95, 81]], dtype=int32)

In [189]:
arr2[[1,2]][:,[3,4]] # 取二三行的四五列

array([[10, 84],
       [59, 63]], dtype=int32)

In [192]:
arr2[:][:,[0,2,4]] # 先默认,然后再取一三五列

array([[95, 97, 10],
       [88, 80, 84],
       [ 3,  9, 63]], dtype=int32)

In [194]:
arr2[2,2] = 1024
arr2 #找到索引改值

array([[  95,   81,   97,   63,   10],
       [  88,   81,   80,   10,   84],
       [   3,   31, 1024,   59,   63]], dtype=int32)

In [197]:
arr2[1,2:4] = 2048
arr2

array([[  95,   81,   97,   63,   10],
       [  88,   81, 2048, 2048, 2048],
       [   3,   31, 1024,   59,   63]], dtype=int32)

In [199]:
arr2[0,[1,4]] = 8096
arr2

array([[  95, 8096,   97,   63, 8096],
       [  88, 8096, 2048, 2048, 8096],
       [   3,   31, 1024,   59,   63]], dtype=int32)

## **花式索引**

In [215]:
arr3 = np.random.randint(0,100,size = 20)
arr3

array([49, 92, 89, 72, 41, 21, 92, 48, 67, 77, 11, 29, 15, 36, 27,  1, 81,
       50,  2, 39], dtype=int32)

In [216]:
arr3[[3,5,7]] # 花式索引

array([72, 21, 48], dtype=int32)

In [218]:
cond = arr3 > 60
arr3[cond] # 取出大于60的数据

array([92, 89, 72, 92, 67, 77, 81], dtype=int32)

In [223]:
# 取出小于30,大于80的数据
cond1 = arr3 > 80
cond2 = arr3 < 30

cond = cond1 | cond2 # 或运算 

arr3[cond]

array([92, 89, 21, 92, 11, 29, 15, 27,  1, 81,  2], dtype=int32)